# Generated by Django 5.2.11 on 2026-03-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_motoboyprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoboyprofile',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor da Diária (R$)'),
        ),
        migrations.AddField(
            model_name='motoboyprofile',
            name='delivery_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Porcentagem por Tele (%)'),
        ),
        migrations.AddField(
            model_name='motoboyprofile',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Mensal (R$)'),
        ),
    ]
