# Generated by Django 5.2.11 on 2026-03-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_motoboyprofile_daily_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoboyprofile',
            name='is_absent',
            field=models.BooleanField(default=False, verbose_name='Ausente?'),
        ),
    ]
