# Generated by Django 5.2.11 on 2026-02-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_serviceorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='routestop',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='stop_type',
            field=models.CharField(choices=[('COLETA', 'Coleta na Origem'), ('ENTREGA', 'Entrega no Destino'), ('TRANSFERENCIA', 'Transferência de Carga'), ('DEVOLUCAO', 'Devolução')], max_length=20),
        ),
    ]
