# Generated by Django 5.2.11 on 2026-02-28 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_motoboyprofile_category'),
        ('orders', '0006_routestop_failure_reason_routestop_is_failed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ositem',
            name='posse_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_em_posse', to='logistics.motoboyprofile'),
        ),
        migrations.AddField(
            model_name='ositem',
            name='status',
            field=models.CharField(choices=[('NAO_COLETADO', 'Não Coletado'), ('COLETADO', 'Coletado (Em posse)'), ('TRANSFERIDO', 'Transferido'), ('ENTREGUE', 'Entregue'), ('RETORNADO', 'Retornado'), ('EXTRAVIADO', 'Extraviado')], default='NAO_COLETADO', max_length=20),
        ),
        migrations.AddField(
            model_name='routestop',
            name='bloqueia_proxima',
            field=models.BooleanField(default=True, help_text='Se True, o motoboy não pode avançar sem resolver esta parada.'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('COM_OCORRENCIA', 'Com Ocorrência'), ('AGUARDANDO_DECISAO', 'Aguardando Decisão'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=25),
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa', models.CharField(choices=[('AUSENTE', 'Destinatário Ausente'), ('NAO_LOCALIZADO', 'Endereço não localizado'), ('RECUSA', 'Mercadoria recusada'), ('ACIDENTE', 'Veículo avariado / Acidente'), ('FECHADO', 'Local Fechado'), ('OUTRO', 'Outro Motivo')], max_length=20)),
                ('subtipo_tags', models.JSONField(blank=True, help_text="Ex: ['Sem internet', 'Área de risco']", null=True)),
                ('observacao', models.TextField(blank=True)),
                ('tentativas_contato', models.PositiveIntegerField(default=0)),
                ('evidencia_foto', models.ImageField(blank=True, null=True, upload_to='ocorrencias/evidencias/')),
                ('urgencia', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta (Crítico)')], default='MEDIA', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvida', models.BooleanField(default=False)),
                ('motoboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.motoboyprofile')),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='orders.routestop')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='orders.serviceorder')),
            ],
        ),
        migrations.CreateModel(
            name='DispatcherDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('REAGENDAR', 'Reagendar tentativa'), ('ALTERAR_ENDERECO', 'Alterar endereço'), ('AUTORIZAR_ALTERNATIVA', 'Autorizar entrega alternativa'), ('RETORNAR', 'Retornar mercadoria'), ('CANCELAR', 'Cancelar OS/Entrega'), ('TRANSFERIR_MOTOBOY', 'Transferir para outro motoboy'), ('CRIAR_PARADA', 'Criar parada extra')], max_length=30)),
                ('detalhes', models.TextField(blank=True)),
                ('decidido_em', models.DateTimeField(auto_now_add=True)),
                ('decidido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('occurrence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decisao', to='orders.occurrence')),
            ],
        ),
    ]
