# Generated by Django 5.2.11 on 2026-03-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ositem_posse_atual_ositem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcherdecision',
            name='acao',
            field=models.CharField(choices=[('REAGENDAR', 'Reagendar tentativa'), ('ALTERAR_ENDERECO', 'Alterar endereço'), ('AUTORIZAR_ALTERNATIVA', 'Autorizar entrega alternativa'), ('RETORNAR', 'Retornar mercadoria'), ('CANCELAR', 'Cancelar OS/Entrega'), ('TRANSFERIR_MOTOBOY', 'Transferir para outro motoboy'), ('CRIAR_PARADA', 'Criar parada extra'), ('VOLTAR_FILA', 'Voltar para a Fila')], max_length=30),
        ),
    ]
