# Generated by Django 5.2.11 on 2026-03-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_dispatcherdecision_acao'),
    ]

    operations = [
        migrations.AddField(
            model_name='osdestination',
            name='delivery_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor da Entrega'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGRUPADO', 'Agrupado'), ('ACEITO', 'OS com o Motoboy'), ('COLETADO', 'Coletado / Em Trânsito'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado'), ('OCORRENCIA', 'Ocorrência / Problema')], default='PENDENTE', max_length=20, verbose_name='Status Atual'),
        ),
    ]
