# Generated by Django 5.2.11 on 2026-03-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_osdestination_delivery_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='custom_address',
            field=models.CharField(blank=True, help_text='Endereço para Devolução ou Ponto de Encontro', max_length=255),
        ),
    ]
