# Generated by Django 5.2.11 on 2026-03-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_routestop_custom_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='custom_complement',
            field=models.CharField(blank=True, help_text='Complemento da Devolução', max_length=255),
        ),
    ]
